server {                   
    listen 443 ssl;       
    listen  [::]:443 ssl;       
    server_name  localhost;
    ssl_certificate /etc/ssl/certs/star_tools_gateway_ga_gov.crt;
    ssl_certificate_key /etc/ssl/private/star_tools_gateway_ga_gov.key;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        add_header 'Strict-Transport-Security' 'max-age=31536000';
    }
}